### ISSUE TITLE
Zoraxy 3.2.5 don't start in the docker container

### ISSUE THREAD

**Issue by conty1337** [tobychui/zoraxy#758]
Summary:
The Docker container for Zoraxy version 3.2.5 fails to start properly due to a repeated FileExistsError when attempting to create a symlink for ZeroTier. This issue does not occur in version 3.2.4, which works as expected.

---

Environment:

Platform: Docker

Zoraxy Version: 3.2.5

Working Version: 3.2.4

---

Steps to Reproduce:

1. Deploy the official Zoraxy Docker image (tag: 3.2.5)

2. Start the container

3. Observe the logs

---

Observed Behavior:

Container enters a crash loop. Each time it tries to start, it fails with the following traceback:

Traceback (most recent call last):
  File "/opt/zoraxy/entrypoint.py", line 127, in <module>
    main()
  File "/opt/zoraxy/entrypoint.py", line 120, in main
    start_zerotier()
  File "/opt/zoraxy/entrypoint.py", line 76, in start_zerotier
    os.symlink(config_dir, zt_path, target_is_directory=True)
FileExistsError: [Errno 17] File exists: '/opt/zoraxy/config/zerotier/' -> '/var/lib/zerotier-one'

The error repeats in a loop and the container exits shortly after each attempt.

---

Expected Behavior:

The container should start normally without crashing, as it does in version 3.2.4. The start_zerotier() function should ideally check for the existence of the symlink or handle the conflict gracefully.

---

Additional Notes:

Downgrading to version 3.2.4 resolves the issue immediately.

The issue appears to be a regression introduced in version 3.2.5 related to symlink creation without checking if it already exists.

**Comment by giss69** [comment]
Hello, 

same hier.

**Comment by AnthonyMichaelTDM** [comment]
this patch should fix it:



```patch
From c982541a402dc446e32b5cc1fa44444128478074 Mon Sep 17 00:00:00 2001
From: Anthony Rubick <68485672+AnthonyMichaelTDM@users.noreply.github.com>
Date: Sun, 20 Jul 2025 23:39:34 -0700
Subject: [PATCH] fix(issue 758): Handle existing symlink in start_zerotier
 function

Fixes #758
---
 docker/entrypoint.py | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)

diff --git a/docker/entrypoint.py b/docker/entrypoint.py
index d6078d9..e476d4b 100644
--- a/docker/entrypoint.py
+++ b/docker/entrypoint.py
@@ -73,7 +73,10 @@ def start_zerotier():
 
   os.makedirs(config_dir, exist_ok=True)
 
-  os.symlink(config_dir, zt_path, target_is_directory=True)
+  try:
+    os.symlink(config_dir, zt_path, target_is_directory=True)
+  except FileExistsError:
+    print(f"Symlink {zt_path} already exists, skipping creation.")
 
   zerotier_proc = popen(["zerotier-one"])
 
-- 
2.50.1
```

**Comment by giss69** [comment]
how to apply patch?))

**Comment by AnthonyMichaelTDM** [comment]
Save that text into a patch file (`fix.patch` or something) and run `git apply fix.patch`, but you're probably better off waiting for a hotfix to be released

**Comment by PassiveLemon** [comment]
Ah this must be because python exits with the error while the previous bash script would continue past it. I've tried to figure out why it happens in the first place and while it only occasionally happens but I cannot figure it out. PR LGTM

**Comment by quorle** [comment]
problem still exists.

Version: Docker:latest

'Updating CA certificates...
Updating GeoIP data...
2025/07/21 23:09:31 Downloading IPv4 database update...
2025/07/21 23:09:31 Downloading IPv6 database update...
2025/07/21 23:09:32 GeoDB update stored at: ./conf/geodb
2025/07/21 23:09:32 Exiting...
Starting ZeroTier...
Traceback (most recent call last):
  File "/opt/zoraxy/entrypoint.py", line 127, in <module>
    main()
  File "/opt/zoraxy/entrypoint.py", line 120, in main
    start_zerotier()
  File "/opt/zoraxy/entrypoint.py", line 76, in start_zerotier
    os.symlink(config_dir, zt_path, target_is_directory=True)
FileExistsError: [Errno 17] File exists: '/opt/zoraxy/config/zerotier/' -> '/var/lib/zerotier-one'
'

**Comment by PassiveLemon** [comment]
This hasn't been pushed yet. Once it is, I will update the tag
